### ISSUE TITLE
Unexpected camel case behaviour

### ISSUE THREAD

**Issue by vim-daniel** [mckacz/yup-env#12]
With the example config 

```
import * as yup from 'yup'
import yupEnv from 'yup-env'

const schema = yup.object()
  .noUnknown()
  .shape({
    some_config: yup.string(),
  })

const config = yupEnv({ schema })
```
`config` will have `someConfig` instead of `some_config`

not sure why to camelCase every env variable, seems like a strange behaviour to me

I think the auto camelCase should be optional WDYT? :)

**Comment by mckacz** [comment]
Hi! I've decided to go with camelCase because most of the coding conventions for JS recommend it. For sure, this behavior will be left as a default one. But... I see your point - there should be an option that allows changing _environment name to object key transformation_ or at least a switch between camelCase and snake_case.

I'll add the support of this feature when I get some free time.

**Comment by mckacz** [comment]
I've just published the beta release that supports snake case keys. You can pull it with `yarn add yup-env@beta` and pass `{keyNamingStrategy: KeyNamingStrategy.snakeCase }` as options.
